### ISSUE TITLE
run project

### ISSUE THREAD

**Issue by xandner** [theringsofsaturn/3D-art-gallery#1]
hello.
i want clone the project and run in my machine.
but when i cloned repository and opened index.html its just stopped in the first page. how can i clone the main repository and run like demo of the project?

**Comment by theringsofsaturn** [comment]
> hello. i want clone the project and run in my machine. but when i cloned repository and opened index.html its just stopped in the first page. how can i clone the main repository and run like demo of the project?

Hi,
As I understood, you are cloning the project that you are trying to run the html with "Open with Live Server" or by clicking "Go live" in VSCode, right? 
Instead, after cloning, open your terminal, and run:
`npm i` to install all the dependencies.
Then type:
`cd src` to change path to src folder
Then run:
`npx vite` to run the local server with Vite. 
You'll see this URL address. like: ` http://127.0.0.1:5173/`. Click it and open the adress in the browser. and your project will be live :) 
<img width="186" alt="image" src="https://user-images.githubusercontent.com/60050952/234292472-7f364dc8-6e77-4094-adde-aed3c4533453.png">
