### ISSUE TITLE
Run on local Webserver without node.js?

### ISSUE THREAD

**Issue by lexterror** [theringsofsaturn/3D-art-gallery#3]
Hi,

I included all deps doesnt seem to run without node.js...

**Comment by theringsofsaturn** [comment]
Hi, 

Without Node.js? No, of course you need Node.js to run a JavaScript project. 
Is there any reason you are not running Node.js on your computer?

**Comment by lexterror** [comment]
im not using a computer. And I thought you could use node.js cdns to run node.js js projects?

**Comment by lexterror** [comment]
do you think you  could add a portable version with all deps included in the future?
